### ISSUE TITLE
larger-scale test of new Rmd support

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/cloc#6]
I filed a PR into the main `cloc` repo (https://github.com/AlDanial/cloc/pull/294) but will be keeping it here regardless of whether it gets incorporated.

Only the lines of code between the triple-backticks clode blocks are included. THe resultant "language" type is `Rmd` as the code blocks could be anything. The results will only be fully accurate for R/Python-ish syntax languages (i.e. the ones supporting the basic `cloc` rules for those languages) but they should be accurate enough for rough estimates for other languages used in Rmd code blocks.

Wondering if anyone (_cough_ @maelle _cough_) has a cadre of R markdown files that they might be willing to give this a major test with. I tend to 'spin' vs 'knit' so my collection is tiny.

**Comment by maelle** [comment]
Mmmh I could extract all vignettes of all ropensci and ropenscilabs packages?

**Comment by hrbrmstr** [comment]
Oh, I was assuming you had a cadre of Rmds due to blogdown (do _not_ go to any trouble for this if that's not the case :-)

**Comment by AlDanial** [comment]
@hrbrmstr : your cloc PR https://github.com/AlDanial/cloc/pull/294 is ready to merge, I'm just waiting for you to add the ``test.Rmd`` and ``test.Rmd.yaml`` files as mentioned in the comment section.  Or am I overlooking something?

**Comment by hrbrmstr** [comment]
aye. once I finalize some work-work things today i'm pushing that back up.
